create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id bigint not null auto_increment, bi varchar(255), birthday date, country varchar(255), email varchar(255), genre integer, hood varchar(255), mobile varchar(255), municipality varchar(255), name varchar(255), nif varchar(255), number_home varchar(255), password varchar(255), province varchar(255), role integer not null, status integer, street varchar(255), primary key (id)) engine=InnoDB
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
