api:
  prefix: /api
  version: v1
  sendgrid:
      key: 
      from: 
spring:
  application:
    name: ProWallet
---
spring:
  profiles: dev-cript
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/walletsec?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Africa/Luanda&useLegacyDatetimeCode=false
    username: root
    password: ps
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create_v2.sql
    show-sql: false
---
spring:
  profiles: docker-sandBox
  datasource:
    url: jdbc:mysql://${host}:${port}/${database}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Africa/Luanda&useLegacyDatetimeCode=false
    username: ${user}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

